---
- hosts: devops
  user: sl
  become: yes
  connection: ssh

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: start apache
      service:
        name: httpd
        state: started
