- name: Install multiple packages on RedHat
  hosts: devops
  user: sl
  connection: ssh
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - git
        - curl
